---
title: "RStudio IDE Tools for Python"
output: 
  rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{RStudio IDE Tools for Python}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(eval = FALSE)
```

<link rel="stylesheet" type="text/css" href="extra.css"/>

## Overview

The current [daily builds](https://dailies.rstudio.com) of RStudio IDE include experimental support for the reticulate package, including:

1) Support for executing Python chunks within R Notebooks

2) 

### Philosophy

A note about the philosophy behind the Python tools within RStudio: these tools are not intended for standalone Python work but rather explicitly aimed at the integration of Python into R projects (as such the tools are closely tied to the reticulate package). 

There are many excellent IDEs for doing data science with Python including JupyterLab, Rodeo, Spyder, and Visual Studio Code, and we strongly recommend using one of them for Python-only projects. However, if you are using "reticulated" Python within an R project then RStudio provides a set of tools that we think you will find extremely helpful.

### Installation

You can download the current daily build of RStudio here: <https://dailies.rstudio.com>

<div class="alert alert-warning">
Note that RStudio daily builds are intended for testing purposes, and are not recommended for general use. If you use the daily build to try out the new Python features please report bugs at <https://github.com/rstudio/rstudio/issues>.
</div>




