# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

py_initialize <- function() {
    invisible(.Call('tensorflow_py_initialize', PACKAGE = 'tensorflow'))
}

py_finalize <- function() {
    invisible(.Call('tensorflow_py_finalize', PACKAGE = 'tensorflow'))
}

py_is_none <- function(x) {
    .Call('tensorflow_py_is_none', PACKAGE = 'tensorflow', x)
}

py_print <- function(x) {
    invisible(.Call('tensorflow_py_print', PACKAGE = 'tensorflow', x))
}

py_is_callable <- function(x) {
    .Call('tensorflow_py_is_callable', PACKAGE = 'tensorflow', x)
}

py_list_attributes <- function(x) {
    .Call('tensorflow_py_list_attributes', PACKAGE = 'tensorflow', x)
}

py_get_attr <- function(x, name) {
    .Call('tensorflow_py_get_attr', PACKAGE = 'tensorflow', x, name)
}

py_get_attribute_types <- function(x, attributes) {
    .Call('tensorflow_py_get_attribute_types', PACKAGE = 'tensorflow', x, attributes)
}

py_to_r <- function(x) {
    .Call('tensorflow_py_to_r', PACKAGE = 'tensorflow', x)
}

py_call <- function(x, args, keywords) {
    .Call('tensorflow_py_call', PACKAGE = 'tensorflow', x, args, keywords)
}

#' Obtain a reference to a python module
#'
#' @param module Name of module
#'
#' @export
py_import <- function(module) {
    .Call('tensorflow_py_import', PACKAGE = 'tensorflow', module)
}

#' Run python code
#'
#' @param code Code to run
#'
#' @export
py_run_string <- function(code) {
    invisible(.Call('tensorflow_py_run_string', PACKAGE = 'tensorflow', code))
}

#' Run python code from a file
#'
#' @param file File to run code from
#'
#' @export
py_run_file <- function(file) {
    invisible(.Call('tensorflow_py_run_file', PACKAGE = 'tensorflow', file))
}

