# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

is_python3 <- function() {
    .Call('reticulate_is_python3', PACKAGE = 'reticulate')
}

#' Get the last Python error encountered
#' 
#' Return a list with the type, value, and traceback for the last
#' Python error encountered (can be `NULL` if no error has yet been
#' encountered).
#' 
#' @export
py_last_error <- function() {
    .Call('reticulate_py_last_error', PACKAGE = 'reticulate')
}

py_is_callable <- function(x) {
    .Call('reticulate_py_is_callable', PACKAGE = 'reticulate', x)
}

r_to_py_impl <- function(object, convert) {
    .Call('reticulate_r_to_py_impl', PACKAGE = 'reticulate', object, convert)
}

py_activate_virtualenv <- function(script) {
    invisible(.Call('reticulate_py_activate_virtualenv', PACKAGE = 'reticulate', script))
}

py_initialize <- function(python, libpython, pythonhome, virtualenv_activate, python3, interactive, numpy_load_error) {
    invisible(.Call('reticulate_py_initialize', PACKAGE = 'reticulate', python, libpython, pythonhome, virtualenv_activate, python3, interactive, numpy_load_error))
}

py_finalize <- function() {
    invisible(.Call('reticulate_py_finalize', PACKAGE = 'reticulate'))
}

py_is_none <- function(x) {
    .Call('reticulate_py_is_none', PACKAGE = 'reticulate', x)
}

py_str_impl <- function(x) {
    .Call('reticulate_py_str_impl', PACKAGE = 'reticulate', x)
}

py_print <- function(x) {
    invisible(.Call('reticulate_py_print', PACKAGE = 'reticulate', x))
}

py_is_function <- function(x) {
    .Call('reticulate_py_is_function', PACKAGE = 'reticulate', x)
}

#' Check if a Python object is a null externalptr
#'
#' @param x Python object
#'
#' @return Logical indicating whether the object is a null externalptr
#' 
#' @details When Python objects are serialized within a persisted R 
#'  environment (e.g. .RData file) they are deserialized into null
#'  externalptr objects (since the Python session they were originally
#'  connected to no longer exists). This function allows you to safely
#'  check whether whether a Python object is a null externalptr. 
#'  
#'  The `py_validate` function is a convenience function which calls
#'  `py_is_null_xptr` and throws an error in the case that the xptr
#'  is `NULL`.
#' 
#' @export
py_is_null_xptr <- function(x) {
    .Call('reticulate_py_is_null_xptr', PACKAGE = 'reticulate', x)
}

#' @rdname py_is_null_xptr
#' @export
py_validate_xptr <- function(x) {
    invisible(.Call('reticulate_py_validate_xptr', PACKAGE = 'reticulate', x))
}

py_numpy_available_impl <- function() {
    .Call('reticulate_py_numpy_available_impl', PACKAGE = 'reticulate')
}

py_list_attributes_impl <- function(x) {
    .Call('reticulate_py_list_attributes_impl', PACKAGE = 'reticulate', x)
}

#' Check if a Python object has an attribute
#'
#' @param x Python object
#' @param name Attribute name
#'
#' @return Logical indicating whether it has the specified attribute
#' @export
py_has_attr <- function(x, name) {
    .Call('reticulate_py_has_attr', PACKAGE = 'reticulate', x, name)
}

py_get_attr_impl <- function(x, name, silent = FALSE) {
    .Call('reticulate_py_get_attr_impl', PACKAGE = 'reticulate', x, name, silent)
}

py_set_attr_impl <- function(x, name, value) {
    invisible(.Call('reticulate_py_set_attr_impl', PACKAGE = 'reticulate', x, name, value))
}

py_get_attribute_types <- function(x, attributes) {
    .Call('reticulate_py_get_attribute_types', PACKAGE = 'reticulate', x, attributes)
}

py_ref_to_r_with_convert <- function(x, convert) {
    .Call('reticulate_py_ref_to_r_with_convert', PACKAGE = 'reticulate', x, convert)
}

py_ref_to_r <- function(x) {
    .Call('reticulate_py_ref_to_r', PACKAGE = 'reticulate', x)
}

py_call_impl <- function(x, args = NULL, keywords = NULL) {
    .Call('reticulate_py_call_impl', PACKAGE = 'reticulate', x, args, keywords)
}

py_dict <- function(keys, items, convert) {
    .Call('reticulate_py_dict', PACKAGE = 'reticulate', keys, items, convert)
}

py_dict_get_item <- function(dict, key) {
    .Call('reticulate_py_dict_get_item', PACKAGE = 'reticulate', dict, key)
}

py_dict_set_item <- function(dict, item, value) {
    invisible(.Call('reticulate_py_dict_set_item', PACKAGE = 'reticulate', dict, item, value))
}

py_dict_length <- function(dict) {
    .Call('reticulate_py_dict_length', PACKAGE = 'reticulate', dict)
}

py_dict_get_keys_as_str <- function(dict) {
    .Call('reticulate_py_dict_get_keys_as_str', PACKAGE = 'reticulate', dict)
}

py_tuple <- function(items, convert) {
    .Call('reticulate_py_tuple', PACKAGE = 'reticulate', items, convert)
}

py_tuple_length <- function(dict) {
    .Call('reticulate_py_tuple_length', PACKAGE = 'reticulate', dict)
}

py_module_import <- function(module, convert) {
    .Call('reticulate_py_module_import', PACKAGE = 'reticulate', module, convert)
}

py_module_proxy_import <- function(proxy) {
    invisible(.Call('reticulate_py_module_proxy_import', PACKAGE = 'reticulate', proxy))
}

py_list_submodules <- function(module) {
    .Call('reticulate_py_list_submodules', PACKAGE = 'reticulate', module)
}

py_iterate <- function(x, f) {
    .Call('reticulate_py_iterate', PACKAGE = 'reticulate', x, f)
}

py_run_string_impl <- function(code, convert = TRUE) {
    .Call('reticulate_py_run_string_impl', PACKAGE = 'reticulate', code, convert)
}

py_run_file_impl <- function(file, convert = TRUE) {
    .Call('reticulate_py_run_file_impl', PACKAGE = 'reticulate', file, convert)
}

